### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite. ts(2589)

### ISSUE THREAD

**Issue by cereallarceny** [saiichihashimoto/sanity-typed#108]
# Overview

[I'm getting the following Typescript error on my schema.](https://github.com/microsoft/TypeScript/issues/34933) This is caused by a single `image` type I'm adding that's deeply nested in my schema. Commenting out this one field causes the type to inference correctly, and having other sibling fields (that aren't images) seems to work perfectly fine. Here's a screenshot of what I'm talking about:

![image](https://github.com/saiichihashimoto/sanity-typed/assets/1297930/581abbe7-1f8f-4361-8baa-8b625046c9ae)

I feel this is likely to be a reflection of Typescript setting a hard, internal limit at the recursive depth it's willing to handle. There's really only two ways around this:

1. Refactor the implementation
2. Find a more efficient way to calculate types

At the moment, I'm hard-wired into my implementation and can't modify it to avoid this problem. Any thoughts on what could be done inside of the `typed` package to support greater depth? I suppose that this could also problem be a problem for `objects` at this same depth, as an `image` is ultimately just an `object` itself.

## Potential Solution/Ideas

Perhaps one way to get around this would to be able to generate intermediary types, so if I have a document called `About` with two inner fields called `Hero` and `Team`, then `InferSchemaValues` would generate 3 types: `About`, `AboutHero`, and `AboutTeam` (which, themselves may have many types internally). I could access the `About` document like this:

```ts
type Values = InferSchemaValues<typeof config>;

export type AboutDocument = Extract<Values, { _type: "about" }>;
```

But I could also extract other "sub-types" of the `About` document like this:

```ts
type Values = InferSchemaValues<typeof config>;

export type AboutDocument = Extract<Values, { _type: "about" }>;

// New
export type AboutHeroSection = Extract<Values, { _type: "about--hero" }>;
export type AboutTeamSection = Extract<Values, { _type: "about--team" }>;
```

In this solution, notice how the `AboutHero` and `AboutTeam` sections are at the same, root level as the `About` document. Anyhow, I have no idea is this would actually solve the problem or if there's a better idea altogether, but that's what I was able to come up with.

**Comment by saiichihashimoto** [comment]
I'll look into this soon!

I don't think your solution does anything new: intermediate types for everything in `defineConfig({ schemas: { types: [...HERE] })` is already being included in `InferSchemaValues`'s output. I'll need to create a minimal repro to really identify what the issue is here. Finding a generic more efficient solution is vague but also very undefined... the current implementations are already mostly magic, it's difficult to understand if this is hitting an unfortunate typescript limit or an inefficiency in this library.

**Comment by saiichihashimoto** [comment]
Can you resend me that config? The link you sent me expired.

**Comment by saiichihashimoto** [comment]
It very much looks like it has to do with objects inside of arrays, somehow. I locally tested having 100 objects nested within one another (it was fine, it broke at 101 but I'm guessing that's a typescript limitation) and it was fine. I tested nesting arrays within one another with a root member of `boolean` (so it was `boolean[][][][][][]...`) and it was fine past 200. The issue was when the member at the very root was an object, (ie `SlugValue[][][][][]...`) it immediately crashed and not even that deep (somewhere at like 3 deep).

**Comment by cereallarceny** [comment]
Hey @saiichihashimoto , I'll email you the config in question. I think it should make sense in context. Sorry for the delay.

**Comment by saiichihashimoto** [comment]
OK @cereallarceny! In #182 I made some changes that improved performance enough to pass those tests reflecting the minimal repro of your config error. Can you verify that this solved your issue?

**Comment by cereallarceny** [comment]
@saiichihashimoto I've migrated to 3.2.3 and can happily report the problem is completely solved! Closing. 😄

**Comment by magicspon** [comment]
@saiichihashimoto I'm seeing this issue with the latest version.

example repo: 

https://github.com/magicspon/sanity-typed-ts-error

**Comment by saiichihashimoto** [comment]
@magicspon let's create a new issue so we don't spam @magicspon. A lot of issues will have the same "type instantiation" error but will likely be different things.

**Comment by magicspon** [comment]
@saiichihashimoto done https://github.com/saiichihashimoto/sanity-typed/issues/242
