### ISSUE TITLE
InferSchemaValues should handle non-object types

### ISSUE THREAD

**Issue by Michael-Janke** [saiichihashimoto/sanity-typed#121]
Hey guys!

I have a schema file for blockContent as in this template: [blockContent.js](https://github.com/sanity-io/sanity/blob/9e30ee3c0869c2f81b1338b4c7a95fa5c75376db/packages/%40sanity/cli/templates/blog/schemas/blockContent.js)

I define it like this:
```ts
import { defineArrayMember, defineType } from '@sanity-typed/types';

export const blockContent = defineType({
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
    defineArrayMember({
      title: 'Block',
      type: 'block',
    }),
    defineArrayMember({
      type: 'image',
      options: { hotspot: true },
    }),
  ],
});
```

Later I want to get the types via 
```ts
export type BlockContent = Extract<Values, { _type: 'blockContent' }>;
```
resolving to `never`.
Also, the fields of type `blockContent` have the type unknown for the working inferred types.

Is it a bug or am I missing something?

**Comment by phmasek** [comment]
I've run into the same issue when the "root" type is an array. When moving the array into an object as such below, it seems to work.

```typescript
import { defineArrayMember, defineField, defineType } from '@sanity-typed/types';

import type { SchemaValues } from '../../sanity.config';

/** 
 * This one works! 
 **/
const BodyComponent = defineType({
  title: 'Body sections',
  name: 'component.body',
  type: 'object',
  fields: [
    defineField({
      name: 'value',
      type: 'array',
      of: [
        defineArrayMember({ name: 'row', type: 'section.row' }),
        defineArrayMember({ name: 'paragraph', type: 'section.paragraph' }),
        defineArrayMember({ name: 'image', type: 'section.image' }),
      ],
    }),
  ],
});


/** 
 * This one doesn't work... 
 **/
const BodyComponent = defineType({
  title: 'Body sections',
  name: 'component.body',
  type: 'array',
  of: [
    defineArrayMember({ name: 'row', type: 'section.row' }),
    defineArrayMember({ name: 'paragraph', type: 'section.paragraph' }),
    defineArrayMember({ name: 'image', type: 'section.image' }),
  ],
});


...

```

**Comment by saiichihashimoto** [comment]
When you look at the signature of the types, it's pretty clear why this doesn't work.

Your example:

```typescript
export type BlockContent = Extract<Values, { _type: 'blockContent' }>;
```

The type you're trying to extract is an array, which won't have a `_type` property on it at all. Any of the non-object types can't really be extracted, but if you inspect `Values`, your array should be in there. You might need a different way of extracting it, maybe `Extract<Values, any[]>` or something more specific to your returned type.

I've been thinking that `InferSchemaValues` needs to change. Right now, it just returns all the `defineType`s as a union, but some of the types are hard to extract, mainly this array. I was under the assumption that the types people use `defineType` for are exclusively objects, but that doesn't seem to be the case. It looks like `InferSchemaValues` shouldn't return a union and instead return something keyed off by type. So if you had a `defineType({ name: 'foo', ... })`, then `InferSchemaValues<typeof config>["foo"]` should be the return type. I've been hesitating because it's another breaking change, but it feels like it handles all use cases.

**Comment by saiichihashimoto** [comment]
For your immediate issue @Michael-Janke and @phmasek, find a different way to extract the type you want out of `Values`. It's there, just without a `_type` on it.

**Comment by phmasek** [comment]
@saiichihashimoto Thanks for the reply! 

Given that the native `defineType` function allows using types other than objects, the name field could be considered a unique identifier for each defined type no matter the use case. It's also motivated by sanity throwing errors if the user is trying to create types sharing the same name. I think your proposed solution is definitely a step in the right direction.

**Comment by Michael-Janke** [comment]
The problem right now is also that if you use this array as a type in the definition of fields, it isn't resolved and is any.
This is for me right now a blocker using this project. This BlockContent type is used in our schema a lot and also I can't change it.

I think if the type for arrays is set to the name of documents and objects, it should fix the problem.
