### ISSUE TITLE
Types defined in third party plugins renders as never

### ISSUE THREAD

**Issue by phmasek** [saiichihashimoto/sanity-typed#124]
The extraction fails and returns `never` when trying to use a type defined in a plugin. Both cases below fails.

### Case 1
```typescript
import { defineType } from '@sanity-typed/types';

import type { SchemaValues } from '../../sanity.config'; // The result of using `InferSchemaValues`

const VideoComponent = defineType({
  title: 'Video',
  name: 'component.video',
  type: 'mux.video',
  preview: {
    select: {
      asset: 'media.asset.data',
    },
  },
});

export default VideoComponent;
export type VideoComponentSchemaType = Extract<SchemaValues, { _type: 'component.video' }>; // This is never
```

### Case 2
```typescript
import { defineField, defineType } from '@sanity-typed/types';

import type { SchemaValues } from '../../sanity.config'; // The result of using `InferSchemaValues`

const VideoComponent = defineType({
  title: 'Video',
  name: 'component.video',
  type: 'object',
  fields: [
    defineField({
      name: 'value',
      type: 'mux.video',
      preview: {
        select: {
          asset: 'media.asset.data',
        },
      },
    }),
  ],
});

export default VideoComponent;
export type VideoComponentSchemaType = Extract<SchemaValues, { _type: 'component.video' }>; // This is also never

```

**Comment by saiichihashimoto** [comment]
The issue is that we can't type these. Until the native sanity `define*` (but mostly `definePlugin`) actually incorporates the types from these libraries, there's no deriving the types from `sanity`'s `define*` method return types. This library exports a `definePlugin` that, if a library were to use directly, would be type-able but, otherwise, there's no real solution here. The objective of this library is to get as much of this directly into `sanity` as possible, which is the only solution for this.

It's also interesting that Case 2 is `never`, though. The fact that we can't type the field shouldn't also untype the video as a whole. If you change the field type to one of the defaults (eg, `mux.video` to `string`) does it return something besides `never`?
