### ISSUE TITLE
Allow native `define*` to be nested (and vice versa)

### ISSUE THREAD

**Issue by jschuur** [saiichihashimoto/sanity-typed#167]
I tried dropping in @sanity-types/types' `defineField` and `defineType` into my schema definitions, but now TS is complaining about schema definition fields added by the [orderable-document-list plugin](https://github.com/sanity-io/orderable-document-list):

```ts
import { defineField, defineType } from '@sanity-typed/types';
import { orderRankField, orderRankOrdering } from '@sanity/orderable-document-list';

const nav = defineType({
  name: 'nav',
  type: 'document',
  title: 'Navigation',
  orderings: [orderRankOrdering],
  fields: [
    // ts2322 error for orderRankField
    orderRankField({ type: 'nav' }),
    defineField({
      name: 'name',
      type: 'string',
      title: 'Name',
      validation: (Rule) => Rule.required(),
    }),
  // ...
```

```
Type '{ type: "string"; name: "orderRank"; } & Omit<StringDefinition, "preview"> & FieldDefinitionBase & WidenValidation & WidenInitialValue' is not assignable to type 'DefinitionBase<any, any, any> & { name: string; [requiredSymbol]?: boolean | undefined; }'.
  Type '{ type: "string"; name: "orderRank"; } & Omit<StringDefinition, "preview"> & FieldDefinitionBase & WidenValidation & WidenInitialValue' is not assignable to type 'DefinitionBase<any, any, any>'.
    Types of property 'validation' are incompatible.
      Type '(ValidationBuilder<StringRule, string> & (false | Rule | SchemaValidationValue[] | ((rule: Rule) => SchemaValidationValue))) | undefined' is not assignable to type 'ValidationBuilder<any, any, any> | undefined'.
        Type 'ValidationBuilder<StringRule, string> & false' is not assignable to type 'ValidationBuilder<any, any, any> | undefined'.
          Type 'ValidationBuilder<StringRule, string> & false' is not assignable to type 'ValidationBuilder<any, any, any>'.
            Types of parameters 'rule' and 'rule' are incompatible.
              Type '{ [x: string]: any; required: () => { [x: string]: any; required: ...; [requiredSymbol]: true; }; [requiredSymbol]: false; }' is missing the following properties from type 'StringRule': min, max, length, uppercase, and 7 more.ts(2322)
```

Should sanity-typed be able to handle this out of the box? Do I need to help it along and define the plugin field types?

#18 seems to talk about this issue, but it's not clear if this is supposed to be fixed/handled in sanity-typed.

**Comment by jschuur** [comment]
Curiously, it's also giving me errors for any `block` types in an array field:

```ts
    defineField({
      name: 'description',
      type: 'array',
      title: 'Description',
      of: [
        {
          // ts2322 error:
          type: 'block',
        },
      ],
    }),
```

```
Type '{ type: string; }' is not assignable to type 'DefinitionBase<any, any, any> & { name?: string | undefined; }'.
  Object literal may only specify known properties, and 'type' does not exist in type 'DefinitionBase<any, any, any> & { name?: string | undefined; }'.ts(2322)
```

**Comment by jschuur** [comment]
> Curiously, it's also giving me errors for any `block` types in an array field:

Created a separate issue for this one: #170

**Comment by saiichihashimoto** [comment]
There's going to be LOTS of issues with plugins that need addressing:

- Since `defineConfig`, `defineType`, `defineField`, `defineArrayMember` and (most notably) `definePlugin` are NOT interchangeable with sanity's native versions (in terms of types, runtime they are). You can't nest this library's `define*` inside of sanity's `define*` or vice versa.
  - This looks like what you're trying to do. `orderRankField` comes from that plugin, which is certainly using `defineField` from sanity, so nesting that in this library's `defineType` just isn't going to work. You could cast it, which might be the best option honestly.
- Someone CAN publish a plugin using `@sanity-typed/types`'s `definePlugin` that will type itself properly. Internally, it needs to use the `define*` functions from this library, *not* from `sanity`.
- The *only* exception to all of this is that you can include sanity's `definePlugin` inside of this library's `defineConfig`, but that's about it. All references to the types will be `unknown`.

These aren't imposed restrictions and aren't things we can get around. The only way is for either this library's or sanity's to be supersets/subsets of one another and ultimately just being a fork. We wouldn't be able to accomplish what we have here, so that's not an option.

Plugins are honestly my biggest problem for this whole library. Getting a user to drop in our `define*` functions in their schema to get wins is easy and great. Getting plugins to do the same seems impossible, especially when it won't be compatible with libraries that aren't using sanity-typed. Ultimately, you won't be able to get types out of a plugin into these types without extra manual effort and casting.

I'm going to close this. Your answer currently lies in casting. There's honestly nothing I can do here that solves this.

**Comment by jschuur** [comment]
> There's going to be LOTS of issues with plugins that need addressing:

@saiichihashimoto Well, thanks for helping me understand that this is a known limitation and that I wasn't just using it wrong.

I'm not sure what I should try casting to. The whole `defineType` parameter object as `SchemaTypeDefinition` from sanity? That didn't seem to help.

I know it's outside the scope of this plugin, but what are my options if I'm using plugins to extract types? sanity-codegen seems on hiatus, and it looks like the output of Sanity's native `defineType` is a type for the schema definition and not the document itsself.

**Comment by saiichihashimoto** [comment]
One thing I thought of is that we _could_ have the typed `define*` allow the untyped `define*`, and do some default logic against it. I feel like this will continually be an issue, so it might be worth pursuing. I had been avoiding this since people are likely to accidentally mix and match where they don’t want to, but I think it’s the only way to handle plugins nicely.

I might also look at having it work the other way too (typed within untyped) just so plugging authors can switch to the typed versions without issues.

I reopened this, just so I can consider it.

I think for your immediate issue, include the plug-in where you usually would and cast that field to `ReturnType<typeof defineField<…>>`. Something like that.

**Comment by saiichihashimoto** [comment]
@jschuur I tested this as well as I could, but #185 should solve your issues. Once you install the new version (semantic-release should post what version it is) you should be able to wrap the `defineField` that is causing issues with `castToTyped(defineField(...))`. In your situation, it should be `castToTyped(orderRankField({ type: 'nav' }))`. Hopefully that works!

**Comment by jschuur** [comment]
> @jschuur I tested this as well as I could, but #185 should solve your issues.

Apologies for not replying to this the other week, @saiichihashimoto. I ended up not bothering with automatic typing for the earlier project and for my personal site that I'm rebuilding with Sanity, I haven't used plugins so far. Will check this out if I do, thanks for adding it!
