### ISSUE TITLE
Wrap a custom client

### ISSUE THREAD

**Issue by romeovs** [saiichihashimoto/sanity-typed#241]
Some usecases require a custom Sanity client.

For instance, I'm using the client from [`next-sanity`](https://github.com/sanity-io/next-sanity), but would like it to be well-typed. 
Could we make it so the underlying client is configurable?

I'm happy to help set up a PR for this if you think that makes sense?

**Comment by saiichihashimoto** [comment]
How would you suggest we accomplish this? Most solutions I can think of require a somewhat convoluted and unmanageable API. Do you have any ideas?

**Comment by romeovs** [comment]
So far, from what I can tell, the sanity client from `@sanity-typed/client` is basically using `createClient` from `@sanity/client` and then wrapping it.

We could add a helper that does the wrapping, but accepts a client as an argument instead?

Could something like this work?

```ts
export const wrapClient =
  <Values extends { [type: string]: any }>() =>
  <const Client extends SanityClient>(client: Client) =>
    client as unknown as SanityClient<
      Config,
      {
        [type in keyof Values]: Extract<Values[type], SanityDocument<any, any>>;
      }[keyof Values][]
    >
```

**Comment by saiichihashimoto** [comment]
I'm of two minds about this.

1. I'm all about this. To the point that I think maybe this should be the default API for anything that's going to require the `const foo = <ProvidedType>() => <DerivedType>(bar: DerivedType) => Bar`, especially since everything in this monorepo is (mostly) about typing existing things. Most of the other things aren't doing things in runtime (`defineType`, `defineField`, etc) but `createClient` specifically is. Chances are, there will be more cases like this.
2. On the other hand, there's lots of room for error. Right now, we're only overriding `fetch` but there are [tons of methods that should also be overwritten with the new types](https://github.com/sanity-io/client/blob/main/src/SanityClient.ts). Chances are, custom clients are going to also overwrite some of these, and we're going to run into a bunch of tickets. `next-sanity` might not be one of these today but, one day, they'll overwrite `create` and I'll get a bunch of tickets for this. It might be better to maintain a `@sanity-typed/next-sanity` so we can handle it, specifically.

Can I ask... even looking at the `next-sanity` documentation, it doesn't look like their `createClient` actually does anything special vs the default `createClient`? It looks like you could replace all of their clients with the default and nothing would be different? I'm familiar with both sanity and nextjs, so I'm lost as to what the true difference is. Any insight `@romeovs`?

**Comment by saiichihashimoto** [comment]
I'm pushing a change that exports `castToTyped` and `castFromTyped` functions, similar to the ones in `@sanity-typed/types`, which effectively does this. Enjoy!

**Comment by saiichihashimoto** [comment]
@romeovs @magicspon @theostrahlen New [`@sanity-typed/next-sanity`](https://github.com/saiichihashimoto/sanity-typed/tree/main/packages/next-sanity) package! Please try it out, I think it addresses your issue, directly.
