### ISSUE TITLE
Passing a `name` or `title` to an `reference` or `object` (in `s.array`) returns Typescript error

### ISSUE THREAD

**Issue by cereallarceny** [saiichihashimoto/sanity-typed#38]
I'm trying to create a reference, but for some reason, Typescript throws a fit when I pass it a `name` and a `title` field:

```ts
{
  name: 'advisors',
  title: 'Advisors',
  type: s.array({
    of: [
      s.reference({
        name: 'advisor', // ts error is here
        title: 'Advisor',
        to: [person],
      }),
    ],
  }),
}
```

To be clear, the code works perfectly, but Typescript is giving me grief:

> Argument of type '{ name: string; title: string; to: [DocumentType<"person", { image: { _type: "image"; asset: Omit<Omit<Reference, "_weak">, "_type"> & { _type: "reference"; }; }; name: string; ... 9 more ...; _updatedAt: string; }, { ...; }, { ...; }>]; }' is not assignable to parameter of type '{ options?: ReferenceOptions | undefined; validation?: ValidationBuilder<TypedValueRule<SanityReference<false>>, SanityReference<false>> | undefined; ... 9 more ...; weak?: false | undefined; }'.
  Object literal may only specify known properties, and 'name' does not exist in type '{ options?: ReferenceOptions | undefined; validation?: ValidationBuilder<TypedValueRule<SanityReference<false>>, SanityReference<false>> | undefined; ... 9 more ...; weak?: false | undefined; }'.ts(2345)
(property) name: string

**Comment by cereallarceny** [comment]
Funny thing - I've actually seen this type issue whenever passing a `name` or a `title` to a `reference` or an `object` when placed inside the `of` key for `s.array()`, like such:

```ts
{
  name: 'competitionLogos',
  title: 'Competition Logos',
  type: s.array({
    of: [
      s.object({
        name: 'logo', // ts error here
        title: 'Logo',
        fields: [
          {
            name: 'name',
            title: 'Name',
            type: s.string(),
          },
          {
            name: 'image',
            title: 'Image',
            type: s.image(),
          },
        ],
      }),
    ],
  }),
},
```

Error:

> Argument of type '{ name: string; title: string; fields: [{ name: "name"; title: string; type: SanityType<{ options: (Omit<StringOptions | undefined, "list"> & { list?: [string | { title: string; value: string; }, ...(string | { ...; })[]] | undefined; }) | undefined; ... 7 more ...; placeholder?: string | undefined; }, string, strin...' is not assignable to parameter of type '{ options?: ObjectOptions | undefined; validation?: ValidationBuilder<TypedValueRule<{ name: string; image: { _type: "image"; asset: Omit<Omit<Reference, "_weak">, "_type"> & { ...; }; }; }>, { ...; }> | undefined; ... 11 more ...; preview?: Preview<...> | undefined; }'.
  Object literal may only specify known properties, and 'name' does not exist in type '{ options?: ObjectOptions | undefined; validation?: ValidationBuilder<TypedValueRule<{ name: string; image: { _type: "image"; asset: Omit<Omit<Reference, "_weak">, "_type"> & { ...; }; }; }>, { ...; }> | undefined; ... 11 more ...; preview?: Preview<...> | undefined; }'.ts(2345)
(property) name: string

**Comment by saiichihashimoto** [comment]
So pretty much everything in `@sanity-typed/schema-builder` returns a _type_, not a _field_. That's why you can throw in `type: s.string()` inside of a field and it works. `s.string()` doesn't take a `name` or a `title` because that's not part of the type. Fields require a `name` and a `title`, but pretty much nothing else does (and doesn't do much with it, either). `reference` and `object` aren't exceptions. They're types, giving them a `name` doesn't make much sense.

There are tons of exceptions, mostly with how sanity works with objects, which are all very weird. The main one is the reason `object` and `objectNamed` both exist. Generally, `object` is used for an unnamed "embedded" objects (when you want a nested object but don't want to register it), where `objectNamed` is when you want to register a type with sanity, so you can use it somewhere else, generally with `type: "myCustomTypeThatMatchesTheName"`. Since this library replaces referencing types by name, that's why `type: myNamedObject({ ... }).ref()` exists. Honestly, object reuse with `objectNamed` isn't really all that necessary. `objectNamed` only makes sense at the same level as `document`. It's also technically not really necessary. Since we can just put `const myObj = s.object({ ...});` in a plain old javascript object, you can just reuse it like a javascript object and avoid a new way of reusing objects.

This library has been a bit pedantic about where you can and can't put `name` and `title`. I had considered loosening it, but then you can run into issues like this:

```typescript
const someDoc = s.document({
  ...,
  fields: [
    {
      name: 'nameOfField',
      type: s.string({ name: 'nameOfType' }),
    },
  ],
});
```

And immediately, there's no good way to identify which value should take precedent. There's not one way to do things, which will get really weird.

This is all to say: this is working as intended. `s.reference` and `s.object` are not meant to have a `name` or `title` directly, and that's intentional.

However, there is something missing which was made note of initially with https://github.com/saiichihashimoto/sanity-typed-schema-builder/issues/218#issuecomment-1526239710. There are properties that don't fit in the type, but still make sense in the context of an array. I might have to make a breaking change for array members, something like:

```typescript
s.array({
  of: [
    {
      type: s.whatever(),
      ..., // Other things, possible name/title? Still not sure why this is needed though, for the UI?
    },
  ],
})
```

Then array member specific properties can be added. Needs some thinking!

**Comment by cereallarceny** [comment]
For what it's worth, I've written a good 4 or 5 issues. I wonder if it would be best we work together to hone in on a few of these problems. I don't doubt that some of them may not be "problems" at all, but rather issues with documentation that led me to do things incorrectly.

Over the weekend, I just finished migrating my entire Sanity Studio over to schema-builder. I've learned a lot about it, but there's either something I'm just categorically not understanding or there are problems with the schema-builder itself. I'd love to help more in documentation, as I feel most of my issues could have been avoided because of it. Would there by any way we could get in touch to collaborate on this? I feel that might be quicker than going back and forth on Github issues saying "works on my machine". 😆

**Comment by saiichihashimoto** [comment]
Yeah, let's do that sometime next week? I'm at a wedding this weekend. I built this thing generally for myself and have opened it up, so I think there's definitely gaps in what it can or can't do. What's the best way to coordinate for you? I'm a google calendar/meet kind of guy but whatever works for you.

**Comment by cereallarceny** [comment]
Sounds great to me @saiichihashimoto. I couldn't find your email online, here's mine, let's coordinate there: me@patrickcason.com

(Github should totally have the ability to DM people...)
