### ISSUE TITLE
How to create types dynamically

### ISSUE THREAD

**Issue by waspeer** [saiichihashimoto/sanity-typed#395]
Hi!

Again, thanks for your work on this package!
I was trying to use this package for a Sanity plugin. The relevant details of this plugin are that you provide it specialized schema types and it spits out a custom schema with a custom input component.

```ts
// sanity.config.ts
// ...

const config = defineConfig({
  // ...
  plugins: [
    slicesPlugin({
      sliceDefinitions: [
        { name: 'hero', fields:  [defineField({ name: 'title', type: 'string' })] },
        { name: 'image', fields:  [defineField({ name: 'image', type: 'image' })] },
      ],
    }),
  ],
});
```

The resulting object schema type is:

```ts
interface Slice {
  _type: 'slice',
  type?: 'hero' | 'image',
  hero__title?: string;
  image__image?: { ... };
}
```

I was trying to create the type of the resulting Slice schema dynamically. I managed to this eventually using `_TypeDefinition` and `_FieldDefinition` but this resulted in the following error:

```
error TS4058: Return type of exported function has or is using name 'required' from external module @sanity-typed/types but cannot be named
```

I'm not sure what this means, but I gather it has something to do with the `required` symbol that is used in the package.

Then I noticed that in a later release the exports of `_TypeDefinition` and `_FieldDefinition` were removed. I do appreciate these are private types and I shouldn't depend on them in my plugin. I also think that creating types dynamically is a valid use case for plugin authors or schema authors that are creating schemas dynamically. Is this something you'd want to support? I'd be happy to brainstorm an API for this with you if I can be of any help.

**Comment by saiichihashimoto** [comment]
I have wavered a bit on the point you're making and defaulted to private because it's easy to make public rather than revert to private. Currently, the public API is the `define*` methods with all the generics inferred. I'm reordering and adding generics constantly and, ultimately, I don't really want to maintain nor encourage any specific set or orderings of the generics. For example, not-so-recently I added `TOptionsHelper` entirely so that inference could pick up some literals, but that would've ended up being a breaking change if I had chosen to make these types public. Since the encouraged usage is for users _not_ to provide or even be aware of these, it makes things a lot easier for me to not be beholden to keeping them consistent.

The `required` symbol is another great example of this: it's a `unique symbol` I'm using to identify if the field is required, but I actually never instantiate it in runtime (the package does nothing in runtime) and only use it for the type. I haven't seen any reason to export any internals unless I happen to use them within other packages in the monorepo, which is what that error is telling you. I could `export` it but then, if you're dependent on it, it's effectively public.

I do also appreciate what you're saying, that there are use cases where external users would want to interact with these types directly, as you are. I don't know how to rectify this: I don't _want_ to maintain a public API for this.

You _could_ import from `@sanity-typed/types/src/internal` to get these back (the underscores are gone now), keep up with any changes I make, and go on your merry way. You might have "breaking" changes without major semver bumps, so hopefully your CI would detect that before you deploy dependency updates.

**Comment by saiichihashimoto** [comment]
I have (for multiple reasons) decided to export `referenced` in #424, so you can use that. I think that handles your immediate issue, although you may have others as you go. You should still be able to import from `@sanity-typed/types/dist/internal`, so hopefully this solves your other issues.
