### ISSUE TITLE
`s.infer` returning unreliable typescript types for simple document schemas

### ISSUE THREAD

**Issue by cereallarceny** [saiichihashimoto/sanity-typed#40]
Given the following document schema:

```ts
import { s } from '@sanity-typed/schema-builder';

import { wysiwyg } from './shared';

export default s.document({
  name: 'page',
  title: 'Page',
  preview: {
    select: {
      title: 'title',
      subtitle: 'lastUpdated.value',
    },
  },
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: s.string(),
    },
    {
      name: 'lastUpdated',
      title: 'Last Updated',
      type: s.object({
        fields: [
          {
            name: 'title',
            title: 'Title',
            type: s.string(),
          },
          {
            name: 'value',
            title: 'Value',
            type: s.string(),
          },
        ],
      }),
    },
    wysiwyg({
      name: 'content',
      title: 'Content',
    }),
  ],
});
```

I get the following types produced via `export type PageDocument = s.infer<typeof page>;`:

```ts
type PageDocument = {
    _type: "page";
    _createdAt: string;
    _id: string;
    _rev: string;
    _updatedAt: string;
}
```

Note that I don't get any types related to `title`, `lastUpdated`, `lastUpdated.title`, `lastUpdated.value`, or `content`.

(For reference on `wysiwyg`, [look at this issue](https://github.com/saiichihashimoto/sanity-typed/issues/37))

**Comment by saiichihashimoto** [comment]
Same issue as https://github.com/saiichihashimoto/sanity-typed/issues/36#issuecomment-1557884527. I suspect the return value of `wysiwyg()` has a type of `{ ..., name: string }` rather than `{ ..., name: 'content' }`, so typescript won't be certain how to name the field and it ends up consuming all the other fields. I think the same suggestion there will solve this too: make `wysiwyg()` return a type instead of a field, and you'll have an easier time.

Just to be clear you _can_ make it return a field. You'll just have to manage the `name` being returned has to be a literal string value yourself. Also, everything else in this library is returning types, so you'll likely end up fighting upstream as you progress.
