### ISSUE TITLE
Webhook validation

### ISSUE THREAD

**Issue by mckelveygreg** [saiichihashimoto/sanity-typed#442]
With the new zod and groq packages, this got me thinking as to how to use @sanity-typed for webhook validation! 

Currently, we have a redundant from scratch zod schema that validates requests. However, I just started refactoring that to use the sanity config derived zod schema! But, I've run into issues because I need to resolve some references in the webhooks, and map those types. 

Webhooks with sanity are already sort of spooky, but having this lib behind webhooks would be awesome! I'm just not sure how to piece it all together? 

---
My current approach is to keep the webhook query in source code, Evaluate it with `@sanity-typed/groq`, and use those types to handle to webhook requests. However, I don't quite understand how to use `Evaluate` (the docs perhaps are stale, there isn't a `dataset` prop available), and would there be a way to derive a zod schema from this result?

```ts
// Parse doesn't seem to like `_type in` queries?
// type Tree = Parse<'*[_type in ["foo", "bar"]] {..., categories[]->{...}, "operation": delta::operation()}'>
type Tree =
  Parse<'*[_type == "foo"]{..., categories[]->{...}, "operation": delta::operation()}'>

type WebhookRequest = Evaluate<
  Tree,
// The generic is expecting context, scope, and this?
  {
    dataset: Extract<VALUES[keyof VALUES], Omit<SanityDocument, "_type">>[]
  }
>
```

Let me know how I could help flesh this out!

**Comment by saiichihashimoto** [comment]
1. `Parse` and `Evaluate` are similar to [`groq-js`'s](https://github.com/sanity-io/groq-js/blob/main/API.md) `parse` and `evaluate`. `Parse` creates an AST, `Evaluate` evaluates it into the type you want, and `EvaluateQuery` will do both at once. So that might be what you're looking for.
2. Yes, to use `Evaluate` properly, you need to provide it a lot more, which isn't documented. If you can parse through it, go for it, but otherwise I think `ExecuteQuery` might be what you need. Although I think you're right that something's up... I'll have to check.
3. There would be no way to derive a zod schema from it. `@sanity-typed/groq` lives entirely in typescript, and there's no way to go from types to runtime, which is where you'd have to construct a zod schema. That's where some kind of `@sanity-typed/groq-zod` would have to live, but I've abandoned my attempt at that (for now) https://github.com/saiichihashimoto/sanity-typed/issues/306
4. Using the existing `@sanity-typed/zod` would also probably be no help. It will only help you validate full documents, where it looks like you're groq-ing for a projection.

I had looked into webhooks in the past and had initially abandoned any attempt at typing them because, yes, they're a bit spooky. I think with the groq package they should be type-able, but there is nothing here that would create a zod schema for you, except if the output is expected to match your documents exactly.

**Comment by saiichihashimoto** [comment]
I looked into this a bit and there's a few things.

Webhooks are defined by a groq query, like you have. Besides all the normal parsing (which is outside of the scope), you can type the resulting body with `EvaluateQuery`. That's a solved problem, so that should be good. Let me know if you need help parsing through the types.

A zod parser is possible but is abandoned in #306. Way too big of a scope.

Other than that, it doesn't seem like there's anything to do with webhooks in terms of typing. Either you type the incoming request or zod parse it. I'm going to close this, let me know if there's anything else you wanted to address.
