### ISSUE TITLE
Should types always be optional?

### ISSUE THREAD

**Issue by LiamMartens** [saiichihashimoto/sanity-typed#488]
Currently the query inferrence is taking into account the validation Rules in the studio, however non nullabilty can really not be guaranteed like they can be in regular database systems.

For this reason I believe it is more accurate to always infer schema types as nullable/optional to ensure implementation always catch null values

Keen to hear your opinion

**Comment by saiichihashimoto** [comment]
The issue with this is that optionality is not the only thing that can't be assured. Changing a schema's type, validation rules, etc can easily happen. There's technically no assurance of any types. Our goal is to reflect the schema's current type. If we want to reflect the type it could be based on previous schemas, the only valid type is `any`.

Your issue is lack of runtime validation, which is what `@sanity-typed/zod` can help with.
