### ISSUE TITLE
Studio in dedicated repo, what to do?

### ISSUE THREAD

**Issue by fcisio** [saiichihashimoto/sanity-typed#685]
Hi, I'm aware that this library is geared towards embedded studio setups.

I won't go into too much detail regarding why I won't embed my studio, this is simply to open a discussion and see if people found solutions to this use case.

I have considered:
- Adding the studio repo as a git submodule to my front-end
  - Adds too much overhead to the main repo, introduces dependency and TS issues
- Publishing the studio config and type exports as a private NPM package
  - Not sure how this would be possible
- I like the approach from [sanity-codegen](https://github.com/ricokahler/sanity-codegen), where actual types are generated via a CLI. That would allow me to copy and paste the types from one repo to the next.
  - Sadly that repo is not stable and doesn't seem to be maintained anymore

Should I face reality and write my types manually? Help

**Comment by saiichihashimoto** [comment]
I definitely need a section in the documentation for this 😂

There is `ts-simplify`, which you can use to get a sort of codegen going with this. It isn't exactly mature, but it was made specifically with this library in mind, so it might be a way to get the copy/paste-able types for you.

I'm guessing you have a private/public concern. You can, when committing your studio, build your types into a private npm package, which your web app would have as a dependency. Private dependencies are... not fun, which is why I usually opt for monorepos or submodules.

It's actually as simple as any two packages depending on each other, which is what you're running into. Git submodules, released (private) package, copy/paste, some kind of codegen, or a monorepo of sorts are generally your only options. My favorite is monorepo but that becomes impossible with private packages or unreasonable if the studio doesn't actually make sense with the app. 

Ultimately, it's up to you how you consume the types and how you structure having code for your app depend on code for your studio. I agree it's not exactly easy but any solution will require some answers for consuming output (in this case, types) from your studio.

**Comment by fcisio** [comment]
Super thorough, I appreciate it.

`ts-simplify` looks promising, I'll have to try it out.

My go-to would also be a monorepo, but sadly I'm working on a Remix Shopify Hydrogen build, which doesn't mix at all with anything other than a regular repo.

I do have some experience with private packages, it is indeed not fun haha. I'll try that option too.
I would just have to figure out the bundling (if you have some input about that, I would gladly listen).

Thanks for the quick response!

**Comment by fcisio** [comment]
For anyone facing this use case in the future, I had great success with a bundle approach.
It turned out to be the most straightforward and stable solution.

I would be happy to provide a basic starter template if needed.

Here is a summary of the solution:
1. Bundle the studio with [`tsup`](https://github.com/egoist/tsup)
2. Set a custom output directory, as to not conflict with the studio build
3. Ship the bundle out

### 3.1. NPM Pack

Now at this stage, I chose to simply ship`.tgz` files. It also meant I didn't have to worry about publishing a private package.

###### -> studio
`npm pack --pack-destination=.studio-versions`

###### -> front-end
```json
"devDependencies": {
    "@my-project/studio": "file:./.studio-versions/studio-0.1.0.tgz",
```

### 3.2. Publish

Publish the package wherever and however you want
