### ISSUE TITLE
Tradeoffs of sanity-typed vs Sanity TypeGen?

### ISSUE THREAD

**Issue by devinhalladay** [saiichihashimoto/sanity-typed#800]
Hi! First of all, thanks for this library. I've used it a few times in the past and loved the developer experience.

I'm writing to ask a simple question: What are the advantages and drawbacks of using sanity-typed versus sanity's new official TypeGen CLI? As far as I can tell, the most concrete difference is that, since sanity-typed is more dynamic, I don't need to write as much boilerplate to achieve full type-safety across my front-end runtime, studio, and sanity client. But what drawbacks are there to this approach over a more traditional codegen system?

For extra context, my Sanity setup is basically a monorepo, with four co-located directories (each is technically a separate git repo). Currently it's setup to generate TS types via Sanity Codegen for each project/repo independently by running a simple bash script.

**Comment by devinhalladay** [comment]
Actually a second part of my question is: Is there any advice on how sanity-typed could be used in combination with Sanity TypeGen? For example it would be sweet if I could easily drop-in the sanity-typed/zod library to use on top of my generated types file

**Comment by saiichihashimoto** [comment]
Thanks for using sanity-typed! I never actually know how much people use it so glad to hear about your uses.

So! I've actually been working on updating sanity-typed and the docs to address this, specifically. So this will be my rough draft. You've hit the nail on the head that it boils down to typegen vs derived types. For something like this there are some pros and cons to both.

- typegen requires generation of a separate file of types before being used, ie a separate build step. In development, this can create a bit of an awkward stutter step for your types to actually register.
- Although, derived types can also suffer, since the complexity can sometimes be slow in the IDE as well.
- With typegen in local development, while it always has to take time to generate your types, once it's generated, it's generated. Meaning, when you load back up your IDE, your types are already there to be picked up, rather than having to be derived all over again. Conversely, if they're out of sync with the rest of your code, everything will be wrong until they're regenerated, which is something you might forget to do often.
- I see you're using a bash script to generate all your types in the monorepo/multiple git repos?? What do you do in dev when you update a schema? Do you have to remember to rerun the script, or do you have some kind of hot reloading going on? Does your CI know to rerun this script? Do you have caching that sometimes breaks? These are the steps that are irrelevant with derived types.
- With typegen, there is something VERY satisfying with seeing your type laid out in plain text. Sometimes helps with debugging, too.
- With derived types, there is something VERY satisfying with updating your schema and seeing it naturally cascade through your codebase. Sometimes helps with debugging, too.
- Derived types are more "natural" than typegen. Derived types are like any other types in your codebase, where you have a "source" for where your types come from, then they can naturally change along with however they're used/pruned/added-to/etc. At one point I was using GraphQL typegen and sanity-typegen (the old one, not the new one) together and the waterfall of types bothered me.
- To me, typegen feels like a consequence of not finding a way to natively type things. Which, admittedly, is very hard with such a dynamic thing like a schema. The codebase of sanity-typed is a good example of something being possible does not mean it is simple.
- Luckily, it looks like both solutions can handle GROQ, which is the harder problem.
- sanity-typed SOMETIMES suffers from typescript's limits when typing GROQ queries. It's a problem I can't find an active solution to, which is very irritating to me.
- Sanity TypeGen is made by sanity, so support and updates are going to be far stronger than sanity-typed.
- The sanity team told me that the types in this library are magic and that I have a ridiculously extensive amount of tests so, while I'm never going to be as up to date or supported as their own codebases, I don't think I'm far off.

You can see that it is mostly opinion and there is no correct answer. I have a harsher opinion that codegen in general feels like a hack (that is often the valid answer!) and I had to see how far I could take avoiding it. I believe there is a way to mix the two, but I haven't approached it yet. Currently, I'm trying to get sanity-typed [up to date with the newest typescript](https://github.com/saiichihashimoto/sanity-typed/pull/787) but it's difficult with all the typescript wizardry I shoved in there. IF YOU KNOW ANY TYPESCRIPT WIZARDS PLEASE SEND THEM HERE.

**Comment by devinhalladay** [comment]
Thanks for the thorough reply @saiichihashimoto! This makes sense. For my purposes I think development velocity is really important, so maybe sanity-typed will be a bit more useful than TypeGen. The fact that I'd have to write my own Zod types on top of codegen files feels like a ton of manual labor I'd love to avoid.

>I see you're using a bash script to generate all your types in the monorepo/multiple git repos?? What do you do in dev when you update a schema? Do you have to remember to rerun the script, or do you have some kind of hot reloading going on? Does your CI know to rerun this script? Do you have caching that sometimes breaks? These are the steps that are irrelevant with derived types.
Yeah we'll have to setup some CI and it pre-/post-commit hooks to enforce codegen on schema changes, which again gets back to the core problem that I just don't want to spend time writing that type of boilerplate.

> With typegen, there is something VERY satisfying with seeing your type laid out in plain text. Sometimes helps with debugging, too.
One thing this made me think is that for devs using sanity-typed, Sanity's Vision tool is going to be an important part of a typical debugging workflow. Just some food for thought as I do feel like going with sanity-typed means sacrificing the ability to clearly see the expected types of things in one place.

**Comment by saiichihashimoto** [comment]
If any of them look at this repro, please apologize to them and let them know I DO know how to break things up into multiple files, I just didn't because I was being a maniac.

**Comment by saiichihashimoto** [comment]
I have, I think Sanity typegen has a place fitting directly into this tool. I haven't figured out exactly how (I haven't dug much into Sanity TypeGen honestly) but I think it shouldn't be too complicated to put them together.

**Comment by saiichihashimoto** [comment]
And yes, getting in-and-out at 1am in Austin during F1 weekend apparently equals a drunk, uninsured, 21 year old t-boning you with a Chevy Silverado at a red light 🤷‍♂️

**Comment by devinhalladay** [comment]
> I have, I think Sanity typegen has a place fitting directly into this tool. I haven't figured out exactly how (I haven't dug much into Sanity TypeGen honestly) but I think it shouldn't be too complicated to put them together.

For what it's worth, I expected to be able to do this:

```
import { structureTool } from "sanity/structure";

import { defineConfig } from "sanity"; // *not* @sanity-typed/types
import type { InferSchemaValues, DocumentValues } from "@sanity-typed/types";
import type GeneratedSanityTypes from "generated-sanity/sanity.types.ts"; // import everything from the sanity typegen types file

import { post } from "./schemas/post";
import { product } from "./schemas/product";

/** No changes using defineConfig */
const config = defineConfig({
  projectId: "59t1ed5o",
  dataset: "production",
  plugins: [structureTool()],
  schema: {
    types: [
      product,
      // ...
      post,
    ],
  },
});

export default config;

/** Typescript type of all types! */
export type SanityValues = InferSchemaValues<typeof GeneratedSanityTypes>; // use generated types instead of the @sanity-typed config
export type SanityDocuments = DocumentValues<SanityValues>;
```

**Comment by saiichihashimoto** [comment]
Yeah, I think the API will look something like that. I think the weirdness is that `GeneratedSanityTypes` more or less IS what `SanityValues` would give you. I think it'll become more relevant in things like `@sanity-typed/client` or `@sanity-typed/groq` where I'd get either the inferred or generated types and derive the query values from it. Something like that!

**Comment by devinhalladay** [comment]
I spent a few hours yesterday trying out sanity-typed, and wanted to share some notes. In the end I think I won't use it for my current project, but would love to in the future.
- As I mentioned, the ability to provide sanity typegen's `sanity.types.ts` to `@sanity-typed/client` or `@sanity-typed/next-sanity` would be helpful
- I didn't realize until way too late that sanity-typed doesn't support IDE completions, which I don't want to give up. Supporting typegen integration could help here too
- Ultimately sanity's native type solutions (typegen + `defineQuery()`) is sufficient for me in terms of code completion and typed queries, and I do like having the type file to browse around (at least in vscode there's currently no way to view/introspect inferred ts types like you can with traditional type definitions)
- However, the main thing I need now is still static type validation. It's really important for my team and sanity doesn't provide good tools for this. Until sanity-typed can support sanity typegen, I think I'm going to use `groq-builder` (the groqd successor) because it generates zod types for me using a query DSL
  - And a small note, I don't want to use their DSL — I like groq's normal string syntax. One reason I initially liked sanity-typed is that it felt like more of a drop-in replacement and doesn't really require me to modify my queries at all

**Comment by devinhalladay** [comment]
Thanks again for the detailed responses! I'll definitely keep an eye on the library and pick it up again in the future if anything I mentioned above is added. Feel free to close this issue, unless you think keeping it open could encourage others to give feedback :)

**Comment by saiichihashimoto** [comment]
Haven't fully read this but wanted to dump this in: [`@sanity-typed/client` works directly with `groq-builder`, if that helps anything](https://www.npmjs.com/package/@sanity-typed/client#usage-with-groqd-actually-groq-builder)

**Comment by saiichihashimoto** [comment]
I'm going to close this in favor of #808[s and heartbreak](https://en.wikipedia.org/wiki/808s_%26_Heartbreak).
