### ISSUE TITLE
Derive objects with `_type`

### ISSUE THREAD

**Issue by metadan** [saiichihashimoto/sanity-typed#96]
As per discussion here: https://sanity-io-land.slack.com/archives/CT03N628J/p1687895922428849

It would be useful to be able to infer types for objects.

It appears the InferSchemaValues call successfully infers the object types, they are just not obviously extractable.

**Comment by saiichihashimoto** [comment]
I'll try and consolidate the explanation in here.

`InferSchemaValues` does infer all of the `defineType` types, including objects. However, `"object"` doesn't have a consistent `_type`, depending on where and how it's used, so that isn't included in the derived type. Often, the `_type` matches the `name` in `defineType`, not all of the time. #69 lists out the various permutations and why we aren't just assuming a `_type`.

The issue here is that it's difficult to actually get the type. `Extract` isn't exactly doing what we want. We could 

1. Go back to deriving types on the individual types rather than the config in general. This creates a whole lot of other issues, like being aware of the other types being referenced, and having to somehow include them manually. Although the API is more obvious, I don't think it's feasible long term. Not something I'm truly considering.
2. Always derive it with `_type` anyways, and just override it in the specific cases it's not involved different. Then, you would always `Extract` against the `_type` and it would just work. Technically, document and object types could collide here, but you likely don't want to do that in sanity anyways. This is the direction I'm leaning in.
3. Have `InferSchemaValues` return something different, perhaps of the shape `{ documents: { [type in typeof keyof documents]: DocumentValue }; objects: { [type in typeof keyof object]: ObjectyValue } }` and you'd end up doing something like `InferSchemaValues<typeof config>["objects"]["typeOfObject"]`. This is fine (and possibly a better API), but is a breaking change and returning the union does feel cleaner.

I think the action to take here is the second option.

**Comment by saiichihashimoto** [comment]
I'm going to edit the title to fit this as well!

**Comment by metadan** [comment]
Just saw these comments and - agree 2nd option sounds the most practical. Thanks for your swift commits. Hope you had a good vacation!

:fire:
